spring:
  application:
    name: todo-app
  data:
    couchbase:
      connection-string: ${COUCHBASE_CONNECTION_STRING}
      username: ${COUCHBASE_USERNAME}
      password: ${COUCHBASE_PASSWORD}
      bucket-name: ${COUCHBASE_BUCKET_NAME}

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  issuer: todo-app
  expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
